sonar.projectKey=helpdesk-application
sonar.projectName=Help Desk Application
sonar.projectVersion=1.0.0

# Source encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=java

# Paths
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.libraries=target/dependency/*.jar

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/*Config.java,**/*Application.java

# Exclusions
sonar.exclusions=**/config/**,**/dto/**

# Code Quality Gate
sonar.qualitygate.wait=true

